from gtts import gTTS                              # import google text to speech lib
import os                                          # to play .wav files using mp123
import pyglet
from time import sleep
from playsound import playsound
# directory where we will save the sound file
directory = "/home/pankaj/Downloads/Summer_of_2020/Chatbot/Conversational-Chatbot-SoC2020/"


# convert the text generated by bot to sppeech
def text_to_speech(text):
	filename = directory + "temp.wav"
	speech = gTTS(text=text, lang= 'en')                       # conversion
	speech.save(filename)            # saving in .wav format
	# os.system("mpg123 " +  directory + "converted_speech.wav") # Playing the converted file 
	music = pyglet.media.load(filename, streaming=False)
	music.play()

	sleep(music.duration) #prevent from killing
	os.remove(filename) #remove temperory file